#!/usr/bin/env python3
from os import path, makedirs, getcwd
from subprocess import run

def cli():

    @command
    def front_start():
        run(['npm', 'start'], cwd='front')

    @command
    def front_install():
        run(['npm', 'install'], cwd='front')

    @command
    def back_start():
        makedirs('testing-folder', exist_ok=True)
        run(['deno', 'run', *deno_flags()], cwd='testing-folder')

    @command
    def back_format():
        run(['deno', 'fmt'], cwd='back')
    
    @command
    def back_lint():
        run(['deno', 'lint'], cwd='back')

    @command
    def build():
        run(['rm', '-rf', getcwd() + '/build'], check=True)
        makedirs('build', exist_ok=True)

        front_install()
        run(['npm', 'run', '-s', 'release'], cwd='front', check=True)
        run(['mv', getcwd() + '/front/dist', getcwd() + '/build/front-static'], check=True)

        back_lint()
        run(['deno', 'compile', *deno_flags('--output', 'build/expenses')], check=True)

    @command
    def install():
        run(['cp', './bin/expenses', '/usr/local/bin/expenses'])

    def deno_flags(*args):
        return [
            '--unstable', '--allow-all',
            '--import-map', path.join(getcwd(), 'back', 'import_map.json'),
            *args,
            path.join(getcwd(), 'back', 'src', 'main.ts')
        ]




# https://gist.github.com/sirikon/d4327b6cc3de5cc244dbe5529d8f53ae
import inspect, sys, os; os.chdir(os.path.dirname(__file__)); commands = []
def spec(f): return inspect.getfullargspec(f)
def command(func): commands.append(func); return func
cli(); args = sys.argv[1:]
if len(args) == 0: print("Available commands:"); [print(' '.join([
    f' {f.__name__}',
    *[f'<{a}>' for a in spec(f).args],
    *([f'<...{spec(f).varargs}>'] if spec(f).varargs is not None else [])
])) for f in commands]; exit(0)
matching_commands = [f for f in commands if f.__name__ == args[0]]
if len(matching_commands) == 0: print(f'Unknown command "{args[0]}"'); exit(1)
try: matching_commands[0](*args[1:])
except KeyboardInterrupt: pass
